import type { Metadata } from "next";
import { yekanBakh, openSans } from "./style/font";
import './css.css'

export const metadata: Metadata = {
  title: "Biomemetic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    suppressHydrationWarning
      lang="en"
      className={`h-full`}
    >
      <body className={`min-h-full flex flex-col ${yekanBakh.variable} ${openSans.variable}`}>{children}</body>
    </html>
  );
}
