import type { Metadata } from "next";
import { yekanBakh, openSans } from "./style/font";
import './globals.css'

export const metadata: Metadata = {
  title: "Biomemetic",
  description: "Generated by create Biomemetic",
  icons: {
    icon: "/favicon.png",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    suppressHydrationWarning
      lang="en"
      className={`h-full`}
    >
      <body style={{ fontFamily: "var(--font-yekan-bakh)" }}  className={`
      ${yekanBakh.variable}
      ${openSans.variable}
      min-h-full
      flex
      flex-col
  `}>{children}</body>
    </html>
  );
}
