import type { Metadata } from "next";
import { yekanBakh, openSans } from "./style/font";
import './global.css'

export const metadata: Metadata = {
  title: "Biomemetic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    suppressHydrationWarning
      lang="en"
      className={`h-full`}
    >
      <body   className={`
    ${yekanBakh.variable}
    ${openSans.variable}
    min-h-full
    flex
    flex-col
  `}>{children}</body>
    </html>
  );
}
